# Board
esp32:
  board: esp32dev
  framework:
    type: arduino

# ESPHome
esphome:
  name: clock
  friendly_name: Clock
  name_add_mac_suffix: true

# Logging
logger:

# Updates
ota:
  - platform: esphome
    password: ""

# Homeassistant
api:
time:
  - platform: homeassistant
    id: current_time

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret captive_portal_ssid
    password: !secret captive_portal_password
captive_portal:

# External components
external_components:
  - source:
      type: local
      path: components

# A default stopwatch
stopwatch:
  id: default_stopwatch
  start:
    name: Stopwatch Start
  stop:
    name: Stopwatch Stop
  reset:
    name: Stopwatch Reset
  running:
    name: Stopwatch Running
  elapsed:
    name: Stopwatch Elapsed

# A default timer
timer:
  id: default_timer
  duration:
    name: Timer Duration
  start:
    name: Timer Start
  pause:
    name: Timer Pause
  stop:
    name: Timer Stop
  state:
    name: Timer State
  remaining:
    name: Timer Remaining
